package dev.kstrahilov.tnavi

import android.content.Intent
import android.os.Bundle
import android.view.View
import android.widget.AdapterView
import android.widget.AdapterView.OnItemClickListener
import android.widget.ArrayAdapter
import android.widget.ListView
import androidx.appcompat.app.AppCompatActivity
import com.google.android.gms.maps.model.LatLng

class ChooseLineActivity : AppCompatActivity(), OnItemClickListener {
    private lateinit var lvLines: ListView

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_choose_line)

        lvLines = findViewById(R.id.lv_lines)
        lvLines.adapter = ArrayAdapter(this, android.R.layout.simple_list_item_1, data())
        lvLines.onItemClickListener = this
    }


    private fun data(): ArrayList<Line> {
        val lines: ArrayList<Line> = ArrayList()

        val route821: ArrayList<Stop> = ArrayList()
        route821.add(Stop("Бл. 407 (Вл-во)"))
        route821.add(Stop("кап. Петко войвода 2"))
        route821.add(Stop("Детелина"))
        route821.add(Stop("Вежен"))
        route821.add(Stop("Мургаш"))
        route821.add(Stop("Армейска"))
        route821.add(Stop("ТИС Север /до ТЦ за ЖПГ/"))
        route821.add(Stop("KAT"))
        route821.add(Stop("Парк-музей Вл. Варненчик"))
        route821.add(Stop("Мебелна палата"))
        route821.add(Stop("В. Ханчев"))
        route821.add(Stop("Петя Дубарова"))
        route821.add(Stop("Георги Петлеешев"))
        route821.add(Stop("Дом Младост"))
        route821.add(Stop("8-ми септември"))
        route821.add(Stop("Техникумите-Сливница"))
        route821.add(Stop("Трансформатора"))
        route821.add(Stop("Л.к. Тракия"))
        route821.add(Stop("Нептун"))
        route821.add(Stop("Централна поща /за ЖПГ/"))
        route821.add(Stop("Димчо Дебелянов"))
        route821.add(Stop("ЖПГ /пл. Славейков за КК/"))

        val route822: ArrayList<Stop> = ArrayList()
        route822.add(Stop("ЖПГ /пл. Славейков за център/"))
        route822.add(Stop("Димчо Дебелянов"))
        route822.add(Stop("Централна поща"))
        route822.add(Stop("Нептун"))
        route822.add(Stop("Л.к. Тракия"))
        route822.add(Stop("Трансформатора"))
        route822.add(Stop("Техникумите-Сливница"))
        route822.add(Stop("8-ми септември"))
        route822.add(Stop("Дом Младост за /Вл-во/"))
        route822.add(Stop("Георги Петлешев"))
        route822.add(Stop("Петя Дубарова"))
        route822.add(Stop("В. Ханчев"))
        route822.add(Stop("Мебелна палата"))
        route822.add(Stop("Парк-музей Вл. Варненчик"))
        route822.add(Stop("КАТ"))
        route822.add(Stop("ТИС Север /до ТЦ за Вл-во/"))
        route822.add(Stop("Армейска"))
        route822.add(Stop("Мургаш"))
        route822.add(Stop("Вежен"))
        route822.add(Stop("Детелина"))
        route822.add(Stop("кап. Петко войвода 2"))
        route822.add(Stop("Скалата"))
        route822.add(Stop("Бл. 407 (Вл-во)"))

        val route823: ArrayList<Stop> = ArrayList()
        route823.add(Stop("ЖПГ /пл. Славейков за център/"))
        route823.add(Stop("Димчо Дебелянов"))
        route823.add(Stop("Централна поща"))
        route823.add(Stop("Нептун"))
        route823.add(Stop("Л.к. Тракия"))
        route823.add(Stop("Трансформатора"))
        route823.add(Stop("Техникумите-Сливница"))
        route823.add(Stop("8-ми септември"))
        route823.add(Stop("Дом Младост за /Вл-во/"))
        route823.add(Stop("Георги Петлешев"))
        route823.add(Stop("Петя Дубарова"))
        route823.add(Stop("В. Ханчев"))
        route823.add(Stop("Мебелна палата"))

        val directions82: ArrayList<Direction> = ArrayList()
        directions82.add(Direction("ЖП Гара", route821, R.raw.jp_gara))
        directions82.add(Direction("Владиславово", route822, R.raw.vladislavovo))
        directions82.add(Direction("Мебелна палата", route823))
        lines.add(Line("82", directions82, announcementFilePath = R.raw._82))

        val route831: ArrayList<Stop> = ArrayList()
        route831.add(Stop("ТИС Север"))
        route831.add(Stop("Осъм"))
        route831.add(Stop("3-ти март"))
        route831.add(Stop("Искър"))
        route831.add(Stop("Янтра"))
        route831.add(Stop("Огоста"))
        route831.add(Stop("Централна автобаза"))
        route831.add(Stop("Дом Младост"))
        route831.add(Stop("8-ми септември"))
        route831.add(Stop("Техникумите-Сливница"))
        route831.add(Stop("Трансформатора"))
        route831.add(Stop("Л.к. Тракия"))
        route831.add(Stop("Нептун"))
        route831.add(Stop("Централна поща /за ЖПГ/"))
        route831.add(Stop("Димчо Дебелянов"))
        route831.add(Stop("ЖПГ /пл. Славейков за КК/"))

        val route832: ArrayList<Stop> = ArrayList()
        route832.add(Stop("ЖПГ /пл. Славейков/"))
        route832.add(Stop("Димчо Дебелянов"))
        route832.add(Stop("Централна поща"))
        route832.add(Stop("Нептун"))
        route832.add(Stop("Л.к. Тракия"))
        route832.add(Stop("Трансформатора"))
        route832.add(Stop("Техникумите-Сливница"))
        route832.add(Stop("8-ми септември"))
        route832.add(Stop("Дом Младост /ул. Вяра/"))
        route832.add(Stop("Централна автобаза"))
        route832.add(Stop("Огоста"))
        route832.add(Stop("Янтра"))
        route832.add(Stop("Искър"))
        route832.add(Stop("3-ти март"))
        route832.add(Stop("Осъм"))
        route832.add(Stop("ТИС Север"))

        val directions83: ArrayList<Direction> = ArrayList()
        directions83.add(Direction("ЖП Гара", route831, R.raw.jp_gara))
        directions83.add(Direction("ТИС Север", route832, R.raw.tis_sever))
        lines.add(Line("83", directions83, R.raw._83))

        val route861: ArrayList<Stop> = ArrayList()
        route861.add(Stop("Почивка /Обръщач/"))
        route861.add(Stop("Почивка-2"))
        route861.add(Stop("Ученически к-с"))
        route861.add(Stop("Средношколска"))
        route861.add(Stop("Стадион Варна"))
        route861.add(Stop("Спортист"))
        route861.add(Stop("Явор"))
        route861.add(Stop("Паметника"))
        route861.add(Stop("Чаталджа"))
        route861.add(Stop("пл. Съединение"))
        route861.add(Stop("Музея"))
        route861.add(Stop("Централна Поща"))
        route861.add(Stop("Полиграфия"))
        route861.add(Stop("8-ми декември"))
        route861.add(Stop("КЗ"))
        route861.add(Stop("ИХА"))
        route861.add(Stop("Лазур"))
        route861.add(Stop("Калин"))
        route861.add(Stop("Любен Каравелов"))
        route861.add(Stop("Народни Будители"))
        route861.add(Stop("Обръщач тролеи"))

        val route862: ArrayList<Stop> = ArrayList()
        route862.add(Stop("Обръщач тролеи"))
        route862.add(Stop("Център"))
        route862.add(Stop("Народни Будители"))
        route862.add(Stop("Любен Каравелов"))
        route862.add(Stop("Калин"))
        route862.add(Stop("Лазур"))
        route862.add(Stop("КЗ"))
        route862.add(Stop("8-ми декември"))
        route862.add(Stop("Полиграфия"))
        route862.add(Stop("Централна поща"))
        route862.add(Stop("Музея"))
        route862.add(Stop("пл. Съединение"))
        route862.add(Stop("Чаталджа"))
        route862.add(Stop("Паметника"))
        route862.add(Stop("Явор"))
        route862.add(Stop("Спортист"))
        route862.add(Stop("Стадион Варна"))
        route862.add(Stop("Средношколска"))
        route862.add(Stop("Карин дом"))
        route862.add(Stop("Ученически к-с"))
        route862.add(Stop("Почивка /Обръщач/"))

        val directions86: ArrayList<Direction> = ArrayList()
        directions86.add(Direction("Аспарухово", route861, R.raw.asparuhovo))
        directions86.add(Direction("Почивка", route862))
        lines.add(Line("86", directions86))

        val route881: ArrayList<Stop> = ArrayList()
        route881.add(Stop("Бл. 407 (Вл-во)"))
        route881.add(Stop("кап. Петко войвода 2"))
        route881.add(Stop("Детелина"))
        route881.add(Stop("Вежен"))
        route881.add(Stop("Мургаш"))
        route881.add(Stop("Армейска"))
        route881.add(Stop("ТИС Север"))
        route881.add(Stop("Осъм"))
        route881.add(Stop("3-ти март"))
        route881.add(Stop("Искър"))
        route881.add(Stop("Янтра"))
        route881.add(Stop("Огоста"))
        route881.add(Stop("Централна автобаза"))
        route881.add(Stop("Дом Младост (за Аспарухово)"))
        route881.add(Stop("8-ми септември"))
        route881.add(Stop("Техникумите-Сливница"))
        route881.add(Stop("Трансформатора"))
        route881.add(Stop("Л.к. Тракия"))
        route881.add(Stop("Нептун"))
        route881.add(
            Stop(
                "Централна поща (за Аспарухово)", location = LatLng(51.4652, 5.452)
            )
        )
        route881.add(Stop("Полиграфия"))
        route881.add(Stop("8-ми декември"))
        route881.add(Stop("КЗ"))
        route881.add(Stop("ИХА"))
        route881.add(Stop("Лазур"))
        route881.add(Stop("Калин"))
        route881.add(Stop("Любен Каравелов"))
        route881.add(Stop("Народни Будители"))
        route881.add(Stop("Обръщач тролеи"))

        val route882: ArrayList<Stop> = ArrayList()
        route882.add(Stop("Аспарухово център"))
        route882.add(Stop("Народни Будители"))
        route882.add(Stop("Любен Каравелов", location = LatLng(51.464239, 5.453679)))
        route882.add(Stop("Калин"))
        route882.add(Stop("Лазур"))
        route882.add(Stop("КЗ"))
        route882.add(Stop("8-ми декември", location = LatLng(43.203468, 27.900332)))
        route882.add(Stop("Полиграфия"))
        route882.add(Stop("Централна поща"))
        route882.add(Stop("Нептун"))
        route882.add(Stop("Л.к. Тракия"))
        route882.add(Stop("Трансформатора"))
        route882.add(Stop("Техникумите-Сливница"))
        route882.add(Stop("8-ми септември"))
        route882.add(
            Stop(
                "Дом Младост /ул. Вяра за Вл-во/", location = LatLng(51.4652, 5.452)
            )
        )
        route882.add(Stop("Централна автобаза"))
        route882.add(Stop("Огоста"))
        route882.add(Stop("Янтра"))
        route882.add(Stop("Искър"))
        route882.add(Stop("3-ти март"))
        route882.add(Stop("Осъм"))
        route882.add(Stop("ТИС Север"))
        route882.add(Stop("Армейска"))
        route882.add(Stop("Мургаш"))
        route882.add(Stop("Вежен"))
        route882.add(Stop("Детелина"))
        route882.add(Stop("кап. Петко войвода 2"))
        route882.add(Stop("Скалата"))
        route882.add(Stop("Бл. 407 (Вл-во)"))

        val directions88: ArrayList<Direction> = ArrayList()
        directions88.add(Direction("Аспарухово", route881, R.raw.asparuhovo))
        directions88.add(Direction("Владиславово", route882, R.raw.vladislavovo))
        lines.add(Line(number = "88", directions = directions88, announcementFilePath = R.raw._88))

        val empty: ArrayList<Stop> = ArrayList()
        val directions999: ArrayList<Direction> = ArrayList()
        directions999.add(Direction("ЗА ДЕПО", empty))
        directions999.add(Direction("СЛУЖЕБЕН", empty))
        directions999.add(Direction("ТЕСТ ДРАЙВ", empty))
        directions999.add(Direction("УЧИЛИЩЕН", empty))
        lines.add(Line("999", directions999))

        val route11: ArrayList<Stop> = ArrayList()
        route11.add(
            Stop(
                "ул. Brunelleschiweg 12",
                location = LatLng(51.465377, 5.452131),
                R.raw._8mi_dekemvri
            )
        )
        route11.add(Stop("Светофара", location = LatLng(51.461966, 5.454300)))
        route11.add(Stop("Джъмбо /Boschdijk/", location = LatLng(51.451085, 5.465096)))
        route11.add(Stop("Пиаца", location = LatLng(51.441186, 5.476073)))

        val route12: ArrayList<Stop> = ArrayList()
        route12.add(Stop("ул. Brunelleschiweg", location = LatLng(51.465377, 5.452131), R.raw._1))
        route12.add(Stop("Площадка", location = LatLng(51.464461, 5.453508), R.raw._2))
        route12.add(Stop("Кръстовище", location = LatLng(51.463444, 5.454460), R.raw._3))
        route12.add(Stop("Светофара", location = LatLng(51.462158, 5.454358), R.raw._4))
        route12.add(Stop("ул. Vignolaweg", location = LatLng(51.466371, 5.451120), R.raw._5))

        val directions1: ArrayList<Direction> = ArrayList()
        directions1.add(Direction("Пиаца", route11))
        directions1.add(Direction("Тест", route12))
        lines.add(Line("1", directions1, R.raw._1))

        return lines
    }

    override fun onItemClick(parent: AdapterView<*>?, view: View?, position: Int, id: Long) {
        val line: Line = data()[position]
        val intent = Intent(this, ChooseDirectionActivity::class.java)
        intent.putExtra("line", line)
        startActivity(intent)
    }
}